// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
package com.cloud.network.ovn.dao;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.cloudstack.api.InternalIdentity;

/**
 * Persisted queue of OVN NB DB rows that failed to delete during a
 * {@code destroy()} / {@code shutdownVpc()} call. A background processor
 * ({@link com.cloud.network.ovn.manager.OvnPendingDeletionProcessor}) retries
 * each row asynchronously so temporary OVSDB failures do not produce permanent
 * orphans.
 *
 * <p>Row lifecycle:
 * <ol>
 *   <li>Inserted when a destroy step throws — {@code removed} is {@code null}.</li>
 *   <li>Updated with {@code attempts++}, {@code last_attempt_at}, {@code last_error}
 *       on each failed retry.</li>
 *   <li>Soft-deleted (set {@code removed = NOW()}) on success so history is
 *       preserved for forensics.</li>
 *   <li>Hard-deleted after the configurable retention window (future GC task;
 *       not implemented in this release).</li>
 * </ol>
 *
 * <p>{@code controller_id = 0} is a sentinel for "any future controller for
 * {@code zone_id}". The processor resolves the actual controller at retry
 * time via {@code OvnPluginManager.findControllerForZone(zoneId)}.
 */
@Entity
@Table(name = "ovn_pending_deletion")
public class OvnPendingDeletionVO implements InternalIdentity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private long id;

    /**
     * UUID for this pending-deletion record. Generated by the application;
     * unique index prevents duplicate enqueue on idempotent retry calls.
     */
    @Column(name = "uuid", nullable = false, length = 40, unique = true)
    private String uuid;

    /**
     * OVN controller owning the target NB DB. Value {@code 0} means
     * "resolve at retry time from {@code zone_id}".
     */
    @Column(name = "controller_id", nullable = false)
    private long controllerId;

    /**
     * CloudStack zone id. Always set so the processor can resolve a
     * fresh controller when {@code controller_id == 0}.
     */
    @Column(name = "zone_id")
    private Long zoneId;

    /**
     * OVN table / entity kind — mirrors {@link OvnLogicalIdMapVO.Kind}.
     */
    @Column(name = "kind", nullable = false, length = 64)
    private String kind;

    /** UUID of the OVN NB DB row to delete. */
    @Column(name = "ovn_uuid", nullable = false, length = 40)
    private String ovnUuid;

    /** CloudStack entity id (network id, vpc id, etc.) for diagnostics. */
    @Column(name = "cs_id")
    private Long csId;

    /** Number of deletion attempts made so far (0 = not yet tried by processor). */
    @Column(name = "attempts", nullable = false)
    private int attempts = 0;

    /** Timestamp of the last attempt; {@code null} before the first processor pass. */
    @Column(name = "last_attempt_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date lastAttemptAt;

    /** Last error message from a failed deletion attempt (truncated to 2048 chars). */
    @Column(name = "last_error", length = 2048)
    private String lastError;

    @Column(name = "created", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date created = new Date();

    /**
     * Soft-delete marker: set to {@code NOW()} on successful deletion.
     * {@code null} = pending; non-null = done.
     */
    @Column(name = "removed")
    @Temporal(TemporalType.TIMESTAMP)
    private Date removed;

    public OvnPendingDeletionVO() {
    }

    public OvnPendingDeletionVO(final String uuid, final long controllerId, final Long zoneId,
                                final OvnLogicalIdMapVO.Kind kind, final String ovnUuid, final Long csId) {
        this.uuid = uuid;
        this.controllerId = controllerId;
        this.zoneId = zoneId;
        this.kind = kind.name();
        this.ovnUuid = ovnUuid;
        this.csId = csId;
    }

    @Override
    public long getId() {
        return id;
    }

    public String getUuid() {
        return uuid;
    }

    public long getControllerId() {
        return controllerId;
    }

    public void setControllerId(final long controllerId) {
        this.controllerId = controllerId;
    }

    public Long getZoneId() {
        return zoneId;
    }

    public void setZoneId(final Long zoneId) {
        this.zoneId = zoneId;
    }

    public OvnLogicalIdMapVO.Kind getKind() {
        return OvnLogicalIdMapVO.Kind.valueOf(kind);
    }

    public String getKindRaw() {
        return kind;
    }

    public String getOvnUuid() {
        return ovnUuid;
    }

    public Long getCsId() {
        return csId;
    }

    public int getAttempts() {
        return attempts;
    }

    public void setAttempts(final int attempts) {
        this.attempts = attempts;
    }

    public Date getLastAttemptAt() {
        return lastAttemptAt;
    }

    public void setLastAttemptAt(final Date lastAttemptAt) {
        this.lastAttemptAt = lastAttemptAt;
    }

    public String getLastError() {
        return lastError;
    }

    public void setLastError(final String lastError) {
        if (lastError == null) {
            this.lastError = null;
        } else {
            this.lastError = lastError.length() > 2048 ? lastError.substring(0, 2048) : lastError;
        }
    }

    public Date getCreated() {
        return created;
    }

    public Date getRemoved() {
        return removed;
    }

    public void setRemoved(final Date removed) {
        this.removed = removed;
    }
}
